### ISSUE TITLE
Need support to set a custom repository (nexus) instead of default one

### ISSUE THREAD

**Issue by pdaugavietis** [IBM-UrbanCode/Node.js-UCD#1]
I'll clean this up and submit a PR shortly, but generally need to support an optional 'npm config set registry xxxxxx' either before or as part of the installation.   Not sure to make parameter of npm install task, or break out to it's own.    I'll play and see.

**Comment by nhmathis** [comment]
If the repository is likely to be changed or modified after installation, then creating a step outside the installation step would be best. In addition, if the "npm config set registry xxxxxxx' step could be expanded to "npm config set xxxxxxx yyyyyyyy" then it would hit more use cases.

**Comment by nhmathis** [comment]
Thanks for your contribution!
